name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_BIN: hugo_extended_0.66.0_Linux-64bit.tar.gz
      TRAVIS_BUILD_DIR:
      GOPATH: $HOME/go
      PATH: $PATH:$GOPATH/bin

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Check go
        run: go version

      - name: Install Hugo ðŸ”§
        run: |
          apt install hugo

      - name: Add Theme
        run: |
          ls -la
          mkdir themes
          git clone --depth 1 https://github.com/robitec/meghna-hugo.git themes/meghna-hugo/

      - name: Add CNAME
        run: |
          ls -la
          hugo -s .
          echo "www.robitec.es" >> public/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          ssh-key: ${{ secrets.DEPLOY_PAGES }}
          folder: public

